# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 500)
        MainWindow.setMinimumSize(QtCore.QSize(300, 500))
        MainWindow.setMaximumSize(QtCore.QSize(300, 500))
        MainWindow.setAutoFillBackground(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.food_input = QtWidgets.QLineEdit(self.centralwidget)
        self.food_input.setGeometry(QtCore.QRect(90, 40, 181, 21))
        self.food_input.setObjectName("food_input")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 40, 47, 13))
        self.label.setObjectName("label")
        self.drink_input = QtWidgets.QLineEdit(self.centralwidget)
        self.drink_input.setGeometry(QtCore.QRect(90, 70, 181, 21))
        self.drink_input.setObjectName("drink_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.label_2.setObjectName("label_2")
        self.dessert_input = QtWidgets.QLineEdit(self.centralwidget)
        self.dessert_input.setGeometry(QtCore.QRect(90, 100, 181, 21))
        self.dessert_input.setObjectName("dessert_input")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 47, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 47, 13))
        self.label_4.setObjectName("label_4")
        self.tip_input10 = QtWidgets.QRadioButton(self.centralwidget)
        self.tip_input10.setGeometry(QtCore.QRect(50, 160, 82, 17))
        self.tip_input10.setChecked(True)
        self.tip_input10.setObjectName("tip_input10")
        self.tip_input15 = QtWidgets.QRadioButton(self.centralwidget)
        self.tip_input15.setGeometry(QtCore.QRect(110, 160, 82, 17))
        self.tip_input15.setObjectName("tip_input15")
        self.tip_input20 = QtWidgets.QRadioButton(self.centralwidget)
        self.tip_input20.setGeometry(QtCore.QRect(170, 160, 82, 17))
        self.tip_input20.setObjectName("tip_input20")
        self.submit_input = QtWidgets.QPushButton(self.centralwidget)
        self.submit_input.setGeometry(QtCore.QRect(30, 390, 75, 23))
        self.submit_input.setObjectName("submit_input")
        self.clear_input = QtWidgets.QPushButton(self.centralwidget)
        self.clear_input.setGeometry(QtCore.QRect(190, 390, 75, 23))
        self.clear_input.setObjectName("clear_input")
        self.text_output = QtWidgets.QLabel(self.centralwidget)
        self.text_output.setGeometry(QtCore.QRect(30, 200, 231, 141))
        self.text_output.setAutoFillBackground(False)
        self.text_output.setText("")
        self.text_output.setScaledContents(False)
        self.text_output.setAlignment(QtCore.Qt.AlignCenter)
        self.text_output.setObjectName("text_output")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Test 10"))
        self.label.setText(_translate("MainWindow", "Food"))
        self.label_2.setText(_translate("MainWindow", "Drink"))
        self.label_3.setText(_translate("MainWindow", "Dessert"))
        self.label_4.setText(_translate("MainWindow", "Tip"))
        self.tip_input10.setText(_translate("MainWindow", "10%"))
        self.tip_input15.setText(_translate("MainWindow", "15%"))
        self.tip_input20.setText(_translate("MainWindow", "20%"))
        self.submit_input.setText(_translate("MainWindow", "SUBMIT"))
        self.clear_input.setText(_translate("MainWindow", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
